title: modzelewski.dev
author: Maciej Modzelewski
#description: >- # this means to ignore newlines until "baseurl:"
#  Modzelewski on software
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://modzelewski.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _MModzelewski
github_username: mmodzelewski
linkedin_username: maciej-modzelewski

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  posts:
    permalink: /:collection/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
